[package]
name = "elven-nft-minter"
version = "0.1.0"
authors = ["Julian Ćwirko <julian.cwirko@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.24.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.24.0"
