[package]
name = "elven-nft-minter-meta"
version = "1.8.0"
authors = ["Julian Ćwirko <julian.io>"]
edition = "2018"
publish = false

[dependencies.elven-nft-minter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
