[package]
name = "elven-nft-minter-meta"
version = "1.6.3"
authors = ["Julian Ćwirko <julian.cwirko@gmail.com>"]
edition = "2018"
publish = false

[dependencies.elven-nft-minter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.31.1"
